
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRIR_GARRA ACTIVAR AGARRAROBJETO ALZARBRAZO ALZARCODO BAJARBRAZO BAJARCODO BASE BRAZO CERRAR_GARRA CODO CUERPO DETENER FIN_REPETIR GARRA GIRAR HOMBRO IDENTIFICADOR IGUAL INICIAR MOVER NUMERO PARENTESIS_A PARENTESIS_C PUNTO REPETIR ROBOT SOLTAROBJETO VELOCIDADlinea : ROBOT IDENTIFICADOR\n             | ROBOT NUMERO IDENTIFICADORlinea : IDENTIFICADOR PUNTO INICIAR PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO DETENER PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO ACTIVAR PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO MOVER PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO CERRAR_GARRA PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO ABRIR_GARRA PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO FIN_REPETIR PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO AGARRAROBJETO PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO SOLTAROBJETO PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO ALZARCODO PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO BAJARCODO PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO ALZARBRAZO PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO BAJARBRAZO PARENTESIS_A PARENTESIS_C\n             | IDENTIFICADOR PUNTO GIRAR PARENTESIS_A PARENTESIS_C\n             linea : IDENTIFICADOR PUNTO VELOCIDAD IGUAL NUMERO\n             | IDENTIFICADOR PUNTO BASE IGUAL NUMERO\n             | IDENTIFICADOR PUNTO CUERPO IGUAL NUMERO\n             | IDENTIFICADOR PUNTO GARRA IGUAL NUMERO\n             | IDENTIFICADOR PUNTO CODO IGUAL NUMERO\n             | IDENTIFICADOR PUNTO HOMBRO IGUAL NUMERO\n             | IDENTIFICADOR PUNTO BRAZO IGUAL NUMERO\n             | IDENTIFICADOR PUNTO REPETIR IGUAL NUMERO\n               | IDENTIFICADOR PUNTO REPETIR PARENTESIS_A NUMERO PARENTESIS_C'
    
_lr_action_items = {'ROBOT':([0,],[2,]),'IDENTIFICADOR':([0,2,5,],[3,4,7,]),'$end':([1,4,7,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,76,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,-25,]),'NUMERO':([2,44,45,46,47,48,49,50,51,52,],[5,67,68,69,70,71,72,73,74,75,]),'PUNTO':([3,],[6,]),'INICIAR':([6,],[8,]),'DETENER':([6,],[9,]),'ACTIVAR':([6,],[10,]),'MOVER':([6,],[11,]),'CERRAR_GARRA':([6,],[12,]),'ABRIR_GARRA':([6,],[13,]),'FIN_REPETIR':([6,],[14,]),'AGARRAROBJETO':([6,],[15,]),'SOLTAROBJETO':([6,],[16,]),'ALZARCODO':([6,],[17,]),'BAJARCODO':([6,],[18,]),'ALZARBRAZO':([6,],[19,]),'BAJARBRAZO':([6,],[20,]),'GIRAR':([6,],[21,]),'VELOCIDAD':([6,],[22,]),'BASE':([6,],[23,]),'CUERPO':([6,],[24,]),'GARRA':([6,],[25,]),'CODO':([6,],[26,]),'HOMBRO':([6,],[27,]),'BRAZO':([6,],[28,]),'REPETIR':([6,],[29,]),'PARENTESIS_A':([8,9,10,11,12,13,14,15,16,17,18,19,20,21,29,],[30,31,32,33,34,35,36,37,38,39,40,41,42,43,52,]),'IGUAL':([22,23,24,25,26,27,28,29,],[44,45,46,47,48,49,50,51,]),'PARENTESIS_C':([30,31,32,33,34,35,36,37,38,39,40,41,42,43,75,],[53,54,55,56,57,58,59,60,61,62,63,64,65,66,76,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'linea':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> linea","S'",1,None,None,None),
  ('linea -> ROBOT IDENTIFICADOR','linea',2,'p_declaracion_robot','parser.py',18),
  ('linea -> ROBOT NUMERO IDENTIFICADOR','linea',3,'p_declaracion_robot','parser.py',19),
  ('linea -> IDENTIFICADOR PUNTO INICIAR PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',41),
  ('linea -> IDENTIFICADOR PUNTO DETENER PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',42),
  ('linea -> IDENTIFICADOR PUNTO ACTIVAR PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',43),
  ('linea -> IDENTIFICADOR PUNTO MOVER PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',44),
  ('linea -> IDENTIFICADOR PUNTO CERRAR_GARRA PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',45),
  ('linea -> IDENTIFICADOR PUNTO ABRIR_GARRA PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',46),
  ('linea -> IDENTIFICADOR PUNTO FIN_REPETIR PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',47),
  ('linea -> IDENTIFICADOR PUNTO AGARRAROBJETO PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',48),
  ('linea -> IDENTIFICADOR PUNTO SOLTAROBJETO PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',49),
  ('linea -> IDENTIFICADOR PUNTO ALZARCODO PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',50),
  ('linea -> IDENTIFICADOR PUNTO BAJARCODO PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',51),
  ('linea -> IDENTIFICADOR PUNTO ALZARBRAZO PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',52),
  ('linea -> IDENTIFICADOR PUNTO BAJARBRAZO PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',53),
  ('linea -> IDENTIFICADOR PUNTO GIRAR PARENTESIS_A PARENTESIS_C','linea',5,'p_accion_sin_parametro','parser.py',54),
  ('linea -> IDENTIFICADOR PUNTO VELOCIDAD IGUAL NUMERO','linea',5,'p_accion_con_parametro','parser.py',64),
  ('linea -> IDENTIFICADOR PUNTO BASE IGUAL NUMERO','linea',5,'p_accion_con_parametro','parser.py',65),
  ('linea -> IDENTIFICADOR PUNTO CUERPO IGUAL NUMERO','linea',5,'p_accion_con_parametro','parser.py',66),
  ('linea -> IDENTIFICADOR PUNTO GARRA IGUAL NUMERO','linea',5,'p_accion_con_parametro','parser.py',67),
  ('linea -> IDENTIFICADOR PUNTO CODO IGUAL NUMERO','linea',5,'p_accion_con_parametro','parser.py',68),
  ('linea -> IDENTIFICADOR PUNTO HOMBRO IGUAL NUMERO','linea',5,'p_accion_con_parametro','parser.py',69),
  ('linea -> IDENTIFICADOR PUNTO BRAZO IGUAL NUMERO','linea',5,'p_accion_con_parametro','parser.py',70),
  ('linea -> IDENTIFICADOR PUNTO REPETIR IGUAL NUMERO','linea',5,'p_accion_con_parametro','parser.py',71),
  ('linea -> IDENTIFICADOR PUNTO REPETIR PARENTESIS_A NUMERO PARENTESIS_C','linea',6,'p_accion_con_parametro','parser.py',72),
]
